

// app/page.js or pages/index.js (depending on your Next.js version)

export default function Home() {
  return (
    <div className="relative h-screen w-full">
      <div 
        className="absolute inset-0 bg-cover bg-center bg-no-repeat"
        style={{
          backgroundImage: "url('/images/download.webp')", // Place your image in the public/images folder
        }}
      >
        <div className="absolute inset-0 bg-black/50"></div> {/* Overlay */}
        <div className="relative h-full flex flex-col items-center justify-center px-4">
          <h1 className="text-white text-5xl font-bold mb-6 text-center">
            Build Your Professional Resume
          </h1>
          <p className="text-white text-2xl text-center">
            Create stunning resumes in minutes with our easy-to-use builder
          </p>
        </div>
      </div>
    </div>
  )
}
export const metadata ={
  title:"ProResume Builder",
  description:"Generated by create next app",
};
